// Items
export const REQUEST_ITEMS = 'REQUEST_ITEMS'
export const RECEIVE_ITEMS = 'RECEIVE_ITEMS'
export const CREATE_ITEM = 'CREATE_ITEM'
export const DELETE_ITEM = 'DELETE_ITEM'
export const UPDATE_ITEM = 'UPDATE_ITEM'
// Authors
export const REQUEST_AUTHORS = 'REQUEST_AUTHORS'
export const RECEIVE_AUTHORS = 'RECEIVE_AUTHORS'
export const CREATE_AUTHOR = 'CREATE_AUTHOR'
export const DELETE_AUTHOR = 'DELETE_AUTHOR'
export const UPDATE_AUTHOR = 'UPDATE_AUTHOR'
// Users
export const REQUEST_USERS = 'REQUEST_USERS'
export const RECEIVE_USERS = 'RECEIVE_USERS'
export const CREATE_USER = 'CREATE_USER'
export const DELETE_USER = 'DELETE_USER'
export const UPDATE_USER = 'UPDATE_USER'

